export const SET_FEED = 'ACTION_SET_FEED';
export const SET_REFRESH_INTERVAL = 'ACTION_SET_REFRESH_INTERVAL';
export const START_REFRESH = 'ACTION_START_REFRESH';
export const STOP_REFRESH = 'ACTION_STOP_REFRESH';
export const UPDATE_DATA = 'ACTION_UPDATE_DATA';
export const SELECT_EVENT = 'ACTION_SELECT_EVENT';
export const SET_REFRESHED_AT_TIME = 'ACTION_SET_REFRESHED_AT_TIME';
